### ISSUE TITLE
error: ‘get_thread_query_string’ was not declared in this scope

### ISSUE THREAD

**Issue by jsanc623** [Tokutek/tokudb-engine#277]
Building with: 

    scripts/make.mysql.bash --mysqlbuild=mariadb-5.5.40-tokudb-7.5.3-linux-x86_64

I get the aforementioned error (see http://i.imgur.com/5fTJCHi.png) at about 80% build. 

I'm using the below to build:

    apt-get install -y gcc cmake build-essential valgrind zlib1g-dev libdb-dev libaio-dev libncurses5-dev bison
    git clone -b releases/tokudb-7.5 https://github.com/Tokutek/tokudb-engine.git
    scripts/make.mysql.bash --mysqlbuild=mariadb-5.5.40-tokudb-7.5.3-linux-x86_64

What am I doing  wrong?

**Comment by prohaska** [comment]
There was a broken RE in the build script (common.sh) that would not use the correct git tag when getting the source.  It is now fixed.  

BTW, we moved bug tracking to JIRA (https://tokutek.atlassian.net/browse/DB) and I created this issue (DB-802) to track this problem.

**Comment by jsanc623** [comment]
Thanks @prohaska! I'll follow the JIRA issue
