### ISSUE TITLE
[Feature Request] LZ4-HC compression

### ISSUE THREAD

**Issue by Profforgr** [Tokutek/tokudb-engine#278]
Hello.

Would be cool to see support for LZ4-HC compression https://github.com/Cyan4973/lz4

It should be useful for read-intensive setups because decompression speed is very fast. I assume compression can be done delayed (to improve insertion speed) - so first insert uncompressed or store in-memory (whenever possible) and compress later.

**Comment by prohaska7** [comment]
We are tracking issues in JIRA.  See https://tokutek.atlassian.net/browse/DB-571

**Comment by Profforgr** [comment]
> We are tracking issues in JIRA. See https://tokutek.atlassian.net/browse/DB-571

Thanks.
