### ISSUE TITLE
commit is slow

### ISSUE THREAD

**Issue by jedy** [Tokutek/tokudb-engine#279]
After any query is performed, commit becomes 100x slow.

test.sql:

```
set profiling=1;
commit;
select * from x;
commit;
commit;
show profiles;
```

x is an arbitrary innodb table.

```
[root@S240 msb_5_6_23]# ./use test < test.sql
i	a
1	1
Query_ID	Duration	Query
1	0.00002975	commit
2	0.00024400	select * from x
3	0.03426450	commit
4	0.02510225	commit
```

Uninstall tokudb engine, then commit becomes normal.

```
[root@S240 msb_5_6_23]# ./use test < test.sql
i	a
1	1
Query_ID	Duration	Query
1	0.00002925	commit
2	0.00092600	select * from x
3	0.00003500	commit
4	0.00002375	commit
```
All variables have default values.

MySQL's version is Percona-Server-5.6.23-rel72.1-Linux.x86_64, tokudb is 7.5.6. Centos 6.5, ext4.

**Comment by prohaska7** [comment]
please post to the tokudb-user community group.

**Comment by BohuTANG** [comment]
Maybe we should move all issues to github.
JIRA is unsocial
